/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zgc.test;

import static org.junit.Assert.*;
import org.junit.Test;

public final class AppTest {
	@Test public final void testAppWIP() {
		App classUnderTest = new App();
	}
}
