/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zgc.test;

import org.junit.Test;
import static org.junit.Assert.*;

public final class AppTest {
	@Test public final void testAppWIP() {
		App classUnderTest = new App();
	}
}
