/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zgc.test;

import org.apache.commons.lang3.time.StopWatch;
import java.util.concurrent.TimeUnit;
import java.util.ArrayList;

public final class App {

	public static final String heap(int run) {
		return "Heap:" + (run == 0 ? "⁰" : run == 1 ? "¹" : "") +
			" " + ((double)Runtime.getRuntime().totalMemory())/(1000*1000*1000) + " GB";
	}

	public static final void println(final Object o) {
		System.out.println(o == null ? "\n" : o);
	}

	public static final void main(final String[] args) {

		lru_cache.test();

		GCinfo.print();
		println("Original " + heap(-1));
		final var c = new lru_cache<Integer>(1000*1000*50);
		for (var i = 0; i < 1000*1000*50; ++i) {
			c.refer(i);
		}

		for (var i = 0; i < 5; ++i) {
			println(null);
			println(heap(0));
			final var g = new GCthread();
			g.start();
			final var stopWatch = new StopWatch();
			stopWatch.start();
			System.gc();
			stopWatch.stop();
			println(heap(1));
			println("Time to perform a full GC: " + stopWatch.getTime() + " ms");
			stopWatch.reset();
		}
	}
}
